name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: >
          javac -d ./out src/*.java
